CREATE TABLE php2.messages (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    title VARCHAR(255),
    content VARCHAR(255),
    user_id INT(11),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE php2.users (
      id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
     name VARCHAR(255),
     email VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);